services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nw.portfolio
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: portfolio_mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - nw.portfolio
    ports:
      - "8080:80"

  php:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/php/dev/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  nginx:
    image: nginx:latest
    container_name: portfolio_nginx
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/nginx/dev/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "25:25"
