services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./infra/volumes/prod/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nw.backend
    ports:
      - "3306:3306"

  php:
    image: app-php
    environment:
      APP_ENV: prod
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      DATABASE_URL: "mysql://root:root@mariadb/app?serverVersion=mariadb-10.5.8"
      MAILER_DSN: "sendmail://default"
    volumes:
      - ./infra/php/prod/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./infra/php/prod/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - nw.backend
      - nw.frontend
    depends_on:
      - mariadb
    tty: true

  nginx:
    image: nginx:1.22
    networks:
      - nw.frontend
    volumes:
      - ./infra/volumes/prod/logs/nginx:/var/log/nginx
      - ./infra/nginx/prod/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - php
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true

networks:
  nw.backend:
  nw.frontend:
