services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./infra/volumes/prod/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nw.portfolio_backend
    ports:
      - "3306:3306"

  php:
    image: app-portfolio-php
    environment:
      APP_ENV: prod
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      DATABASE_URL: "mysql://root:root@mariadb/portfolio?serverVersion=mariadb-10.5.8"
      MAILER_DSN: "sendmail://default"
      GOOGLE_RECAPTCHA_SITE_KEY: "6Lc0_64ZAAAAAFnJ9-nQ_r1F6hdlG-bSt297kJ1j"
      GOOGLE_RECAPTCHA_SECRET: "6Lc0_64ZAAAAAHYotZQyNJECKrtA0a7aB0-_VHku"
      RECAPTCHA3_KEY: "6Lc0_64ZAAAAAFnJ9-nQ_r1F6hdlG-bSt297kJ1j"
      RECAPTCHA3_SECRET: "6Lc0_64ZAAAAAHYotZQyNJECKrtA0a7aB0-_VHku"
      GOOGLE_TAG_MANAGER_ID: "G-JNY6VGP4EQ"
    networks:
      - nw.portfolio_backend
      - nw.portfolio_frontend
    depends_on:
      - mariadb
    tty: true

  nginx:
    image: app-portfolio-nginx
    networks:
      - nw.portfolio_frontend
    volumes:
      - ./infra/volumes/prod/logs/nginx:/var/log/nginx
    volumes_from:
      - php
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true

networks:
  nw.portfolio_backend:
  nw.portfolio_frontend:
