services:
  minecraft:
    build:
      context: .
    volumes:
      - ./server:/server
    command: > 
      sh -c "chmod 755 start-server.sh && 
             ./start-server.sh && 
             tail -f /dev/null"
    ports:
      - 25565:25565