services:
  steamcmd:
    build:
      context: .
    tty: true
    command: tail -f /dev/null
    volumes:
      - ./steam-servers:/home/steam/steam-servers
    ports:
      - 7777:7777/udp
      - 27020:27020/tcp