services:
  vite:
    build:
      context: ./infra/dev/vite
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./app:/var/www/app

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
