services:
  mysql:
    container_name: db
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nw.backend

  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./infra/volumes/prod/composer:/root/.composer
      - ./infra/php/prod/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./infra/php/prod/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
    depends_on:
      - mysql
    tty: true
    networks:
      - nw.backend
      - nw.frontend

  nginx:
    image: nginx:latest
    volumes_from:
      - php
    volumes:
      - ./infra/volumes/prod/logs/nginx:/var/log/nginx
      - ./infra/nginx/prod/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    tty: true
    networks:
      - nw.frontend


volumes:
  mysql_data:

networks:
  nw.backend:
  nw.frontend: